language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PINS="mimic.dev:. carton.dev:. carton-lwt.dev:. carton-git.dev:. git.dev:. git-unix.dev:. git-cohttp.dev:. git-cohttp-unix.dev:. git-mirage.dev:. git-cohttp-mirage.dev:."
  matrix:
    - OCAML_VERSION=4.08 PACKAGE="git.dev"
    - OCAML_VERSION=4.09 PACKAGE="git.dev"
    - OCAML_VERSION=4.10 PACKAGE="git.dev"
    - OCAML_VERSION=4.08 PACKAGE="git-unix.dev"
    - OCAML_VERSION=4.08 PACKAGE="git-unix.dev"
    - OCAML_VERSION=4.08 PACKAGE="git.dev" REVDEPS=*
    - OCAML_VERSION=4.08 PACKAGE="git-mirage.dev" TESTS=false POST_INSTALL_HOOK=./.test-mirage.sh
