language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PINS="git.dev:. git-http.dev:. git-unix.dev:. git-mirage.dev:. encore.dev:https://github.com/dinosaure/encore.git"
  matrix:
    - OCAML_VERSION=4.06 PACKAGE="git.dev"
    - OCAML_VERSION=4.04 PACKAGE="git-unix.dev"
    - OCAML_VERSION=4.03 PACKAGE="git-unix.dev"
    - OCAML_VERSION=4.04 PACKAGE="git-mirage.dev"
    - OCAML_VERSION=4.05 PACKAGE="git.dev" REVDEPS=*
